// transformed/vue/components/atoms/button/Button.vue
```html
<template>
  <button
    class="atom-button"
    :disabled="!enabled"
    @click="handleClick"
    v-bind="props"
  >
    {{ label }}
  </button>
</template>

<script>
export default {
  name: 'Button',
  props: {
    label: {
      type: String,
      required: true
    },
    enabled: {
      type: Boolean,
      default: true
    },
    onClick: {
      type: Function,
      required: true
    },
    props: {
      type: Object
    }
  },
  methods: {
    handleClick() {
      if (this.enabled) {
        this.onClick();
      }
    }
  }
};
</script>

<style scoped>
.atom-button {
  /* Add your Button.css styles here */
}
</style>
```

// transformed/react/components/atoms/button/Button.tsx
import React from 'react';
import './Button.css';

interface ButtonProps {
  label: string;
  enabled?: boolean;
  onClick: () => void;
}

const Button: React.FC<ButtonProps> = ({ label, enabled = true, onClick, ...props }) => {
  return (
    <button
      className="atom-button"
      disabled={!enabled}
      onClick={enabled ? onClick : undefined}
      {...props}
    >
      {label}
    </button>
  );
};

export default Button;
