// intermediate/vue/molecules/Accordion/Accordion.vue
```html
<template>
  <div class="molecule-accordion">
    <div 
      class="accordion-title" 
      :class="{ open: isOpen }" 
      @click="toggleAccordion"
    >
      {{ title }}
    </div>
    <div v-if="isOpen" class="accordion-content">
      <slot></slot>
    </div>
  </div>
</template>

<script>
export default {
  props: {
    title: String,
    open: {
      type: Boolean,
      default: false
    }
  },
  data() {
    return {
      isOpen: this.open
    };
  },
  methods: {
    toggleAccordion() {
      this.isOpen = !this.isOpen;
    }
  }
};
</script>

<style scoped>
.molecule-accordion {
  /* Add your styles here */
}

.accordion-title {
  /* Add your styles here */
}

.open {
  /* Add your styles here */
}

.accordion-content {
  /* Add your styles here */
}
</style>
```

// intermediate/react/molecules/Accordion/Accordion.tsx
import React, { useState, ReactNode } from 'react';
import './Accordion.css';

interface AccordionProps {
  title: string;
  content: ReactNode;
  open?: boolean;
}

const Accordion: React.FC<AccordionProps> = ({ title, content, open = false }) => {
  const [isOpen, setIsOpen] = useState<boolean>(open);

  const toggleAccordion = () => {
    setIsOpen(!isOpen);
  };

  return (
    <div className="molecule-accordion">
      <div 
        className={`accordion-title ${isOpen ? 'open' : ''}`} 
        onClick={toggleAccordion}
      >
        {title}
      </div>
      {isOpen && (
        <div className="accordion-content">
          {content}
        </div>
      )}
    </div>
  );
};

export default Accordion;
